pluginManagement {
    repositories {
        maven { name = "Architectury"; url = "https://maven.architectury.dev/" }
        maven { name = "Fabric";       url = "https://maven.fabricmc.net/" }
        maven { name = "NeoForged";    url = "https://maven.neoforged.net/releases/" }
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id "org.gradle.toolchains.foojay-resolver-convention" version "0.8.0"
}

rootProject.name = "set-home-waypoints"

include("common")
include("fabric")
include("neoforge")
